apiVersion: v2
name: neverending-blog
description: A Helm chart to deploy the NeverEnding Blog
type: application
# HelmChart Version
version: 1.0.1
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.1
dependencies:
- name: postgresql
  version: "1.0.0"
  repository: "https://whoacademy.github.io/helm-charts"
maintainers:
  - name: mabulgu
