---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    build: {{ .Values.app_name }}
    app: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    build: {{ .Values.app_name }}
    app: {{ .Values.app_name }}
    type: 'image'
  name: {{ .Values.app_name }}
spec:
  nodeSelector:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.app_name }}:{{ .Values.build.build_tag | default "latest"}}'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
      binary: {}
      type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.build.base_image }}
        namespace: openshift
    type: Source
  triggers: []
